version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: classly-db
    restart: always
    environment:
      # Docker Compose מושך את המשתנים האלו מה-env. של השרת/shell
      POSTGRES_USER: itay
      POSTGRES_PASSWORD: ${DB_PASSWORD} # נגדיר ב-env הראשי
      POSTGRES_DB: classly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./studio_management_schema_setup.sql:/docker-entrypoint-initdb.d/setup.sql

  backend:
    build: ./server
    container_name: classly-api
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./client
      args:
        - VITE_API_URL=https://www.classly-studio-management.uk/api
    container_name: classly-web
    restart: always
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - backend

volumes:
  postgres_data: