#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run lint-staged and tests in client/
echo "Running pre-commit checks in client..."
cd client
npx lint-staged
npm run typecheck
npm run test:unit

# Run lint-staged and tests in server/
echo "Running pre-commit checks in server..."
cd ../server
npx lint-staged
npm run typecheck
npm run test:unit
